[package]
name = "xdelta_lui"
version = "1.1.5"
edition = "2021"

[dependencies]
adw = { version = "=0.4.4", package = "libadwaita", features = ["v1_4", "gtk_v4_10"] }
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_10"] }
